### ISSUE TITLE
Issue in app level build.gradle

### ISSUE THREAD

**Issue by nrd26** [data-charya/Elemental#10]
**Describe the bug**
app level build.gradle shows an error for storeFile. Commenting out this line lets the app run on the emulator but continually shows errors on the Run Console in Android Studio while on the homepage. 
The errors are Render Errors due to calling the toDouble function on null. I suspect it's an issue with the 'Wanna know something cool' part which never loads (atleast for me)

**To Reproduce**
1. Clone repo
2.Run on Android Studio on a device

**Expected behavior**
An error free run

**Screenshots**
![elemental_error](https://user-images.githubusercontent.com/58399987/156236608-f6afe62e-eb75-41f5-95d2-bf55ac8e8837.png)
![image](https://user-images.githubusercontent.com/58399987/156237665-2e02286d-c880-45c1-8acd-8aedf078e388.png)

**Comment by data-charya** [comment]
Yes, it's because the domain has been changed for the API. Also, I had plans to change that page to something better. Probably will work on it soon.

**Comment by MnCSSJ4x** [comment]
can I work on this issue ?

**Comment by data-charya** [comment]
@MnCSSJ4x  I have assigned this issue to you

**Comment by MnCSSJ4x** [comment]
> @MnCSSJ4x I have assigned this issue to you

Can someone describe the issue a bit as of what is is and what is exactly causing this
