### ISSUE TITLE
Directories and files naming convention

### ISSUE THREAD

**Issue by hazemtarekelaswad** [data-charya/Elemental#14]
### Description

The files and directories naming is not consistent and does not follow the flutter style guide found in the link below.

https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo 

### Domain

Android (Flutter)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/data-charya/Elemental/blob/master/CODE_OF_CONDUCT.md) of this project. 

#15

**Comment by data-charya** [comment]
Closing this issue
