### ISSUE TITLE
Can I contribute to this project either after GSSOC?

### ISSUE THREAD

**Issue by seifibrahim32** [data-charya/Elemental#16]
### Description

Can I contribute to this project either after GSSOC?

### Domain

Android (Flutter)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/data-charya/Elemental/blob/master/CODE_OF_CONDUCT.md) of this project.

**Comment by seifibrahim32** [comment]
@data-charya ?? Can I still contribute to GSSoC22?

**Comment by data-charya** [comment]
Sure @seifibrahim32
