### ISSUE TITLE
Your product is good, but I think your promotional video is better! That's cool! Can you share how you made this promotional video? What software do you need? thank you!

### ISSUE THREAD

**Issue by guolidaxian** [data-charya/Elemental#6]
Your product is good, but I think your promotional video is better! That's cool! Can you share how you made this promotional video? What software do you need? thank you!

**Comment by data-charya** [comment]
Thank you @guolidaxian , I made the video using Adobe After Effects.

**Comment by guolidaxian** [comment]
> Adob​​e After Effects

1. Thank you very much！
