### ISSUE TITLE
Promo

### ISSUE THREAD

**Issue by Lakhankumawat** [data-charya/Elemental#7]
Hi @data-charya  please tell me which tool you used for promo video of your app in README

**Comment by data-charya** [comment]
Adobe After Effects

**Comment by Lakhankumawat** [comment]
Looks great bro , but you made all of it on your own or used some template .

**Comment by data-charya** [comment]
I had to get it done quick so did it via a template

**Comment by Lakhankumawat** [comment]
Could you please provide template link if it is public , please , btw your promo is awesome .
