### ISSUE TITLE
API  , BLoC State Management , SharedPreferences usage

### ISSUE THREAD

**Issue by seifibrahim32** [data-charya/Elemental#8]
Making APIs for the app so as when the user logs in we give options like favorite elements...
and the elements appear with the informstion for each elements like valency and et cetera.....
BLoC state managrment wilk decrease the setState()....
seifibrahim32@gmail.com

**Comment by data-charya** [comment]
I have assigned the issue to you @seifibrahim32

**Comment by seifibrahim32** [comment]
It will be done with days....

**Comment by seifibrahim32** [comment]
hi

**Comment by seifibrahim32** [comment]
Can i continue contribution ?

**Comment by seifibrahim32** [comment]
assign me this and re open again
