### ISSUE TITLE
Spacing issues

### ISSUE THREAD

**Issue by nrd26** [data-charya/Elemental#9]
**Describe the bug**
I noticed a few spacing issues in the app where the layout doesn't display according to screen size but has hardcoded values for it

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the app on Android Studio or any other IDE of your choice
2. View the app through your emulator or mobile device(I viewed it on a Google Pixel Emulator and a Samsung Galaxy A50. Different issues showed on both these devices)
3. Navigate to the 3rd page in the bottom navigation bar to view the spacing between the Bottom Nav Bar and the Elements list
4. Navigate to the 2nd page, click on the search bar to see a pixel overflowed error.
5.  Type a letter on the same search bar to see the element list. Press the mobile back button to see the spacing between the Bottom Nav Bar and the elements list.
6. Navigate to the 4th page. The developer description doesn't display fully.

**Expected behaviour**
There shouldn't be spacing between the lists and the bottom nav bar and in other places

**Screenshots**

![Screenshot_1646143721](https://user-images.githubusercontent.com/58399987/156185647-527d3722-d96c-4486-86d8-48aece0918e7.png)
![Screenshot_1646143747](https://user-images.githubusercontent.com/58399987/156185665-fb4d17bb-b77a-4a78-bd74-fc1b0b053216.png)
![Screenshot_1646143759](https://user-images.githubusercontent.com/58399987/156185675-61301cf3-490e-491f-ad96-673a166295cf.png)

If possible, I would love to work on this issue and solve it as soon as possible

**Comment by data-charya** [comment]
Sure please do go ahead. I am assigning this issue to you.
